### ISSUE TITLE
您好，关于数据集的问题

### ISSUE THREAD

**Issue by xklg309** [fengyang95/AIC_Weather_Forecasting#1]
您好，感谢您无私的分享代码，看了您的代码，受益匪浅，但是目前AI2018的官网数据集的无法下载，您是否方便提供一下数据集的下载地址呢，万分感谢

**Comment by fengyang95** [comment]
不好意思哈 不清楚这个数据涉不涉及法律问题 不敢乱给 最好等官网好了去官网下载吧
